version: "3.3"
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    volumes:
      - ./kfdata:/kafka
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  app:
    image: fit_changes-be-ktor-product:0.0.1
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    links:
      - zookeeper
      - kafka
    environment:
      KAFKA_HOSTS: kafka:9092
      KAFKA_TOPICS_IN: product-in
      KAFKA_TOPICS_OUT: product-out

  appKafkaTest:
    image: test_kafka:0.0.1
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    links:
      - zookeeper
      - kafka
    environment:
      KAFKA_HOSTS: kafka:9092
      KAFKA_TOPICS_IN: product-out
      KAFKA_TOPICS_OUT: kafka-test


  kafdrop:
    image: obsidiandynamics/kafdrop:3.28.0
    ports:
      - "9000:9000"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"