openapi: 3.0.3
info:
  title: Product
  description: 'Description of the transport model of the product'
  version: 0.0.1
paths:
  /create:
    post:
      tags:
        - product
      summary: Create a new product
      operationId: createProduct
      requestBody:
        description: The request object to create a new product
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductRequest'
        required: true
      responses:
        200:
          description: All responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateProductResponse'
  /read:
    post:
      tags:
        - product
      summary: Get information about an product
      operationId: readProduct
      requestBody:
        description: The request object to obtain an product information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReadProductRequest'
        required: true
      responses:
        200:
          description: All responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadProductResponse'

components:
  schemas:

    CreatableProduct:
      type: object
      description: The structure with data about the product to request about creation
      properties:
        productName:
          type: string
          description: Product name
        caloriesPerHundredGrams:
          type: number
          format: double
          description: Product calorie content
        proteinsPerHundredGrams:
          type: number
          format: double
          description: Product protein content
        fatsPerHundredGrams:
          type: number
          format: double
          description: Product fat content
        carbohydratePerHundredGrams:
          type: number
          format: double
          description: Product carbohydrate content

    UpdatableProduct:
      description: Structure for a data about the product in request to update
      allOf:
        - $ref: '#/components/schemas/CreatableProduct'
        - type: object
          properties:
            id:
              type: string
              description: ID of the updated object

    CreateProductRequest:
      allOf:
        - $ref: './spec-fitChanges-api.yaml#/components/schemas/BaseMessage'
        - $ref: './spec-fitChanges-api.yaml#/components/schemas/BaseRequest'
        - type: object
          properties:
            createProduct:
              $ref: '#/components/schemas/CreatableProduct'
            debug:
              type: object
              properties:
                stub:
                  type: string
                  enum:
                    - success
                    - error

    CreateProductResponse:
      description: The structure to respond to a request about the declaration an product
      allOf:
        - $ref: './spec-fitChanges-api.yaml#/components/schemas/BaseMessage'
        - $ref: './spec-fitChanges-api.yaml#/components/schemas/BaseResponse'
        - type: object
          properties:
            createProduct:
              $ref: '#/components/schemas/ResponseProduct'

    ResponseProduct:
      description: The structure describing the product in the response
      allOf:
        - $ref: '#/components/schemas/UpdatableProduct'
        - type: object
          properties:
            permissions:
              type: array
              uniqueItems: true
              items:
                $ref: './spec-fitChanges-api.yaml#/components/schemas/Permissions'

    ReadProductRequest:
      description: The structure to get product
      allOf:
        - $ref: './spec-fitChanges-api.yaml#/components/schemas/BaseMessage'
        - $ref: './spec-fitChanges-api.yaml#/components/schemas/BaseRequest'
        - type: object
          properties:
            readProductId:
              type: string
            debug:
              allOf:
                - $ref: './spec-fitChanges-api.yaml#/components/schemas/BaseDebugRequest'
                - type: object
                  properties:
                    stub:
                      type: string
                      enum:
                        - success
                        - emptyId
                        - errorDb
    ReadProductResponse:
      description: The structure to respond to a request with an product information
      allOf:
        - $ref: './spec-fitChanges-api.yaml#/components/schemas/BaseMessage'
        - $ref: './spec-fitChanges-api.yaml#/components/schemas/BaseResponse'
        - type: object
          properties:
            readProduct:
              $ref: '#/components/schemas/ResponseProduct'