POST http://127.0.0.1:8080/product/create
Content-Type: application/json

{
  "messageType": "CreateProductRequest",
  "requestId": "rID:0001",
  "createProduct": {
    "productName": "Говядина",
    "caloriesPerHundredGrams": "187.0",
    "proteinsPerHundredGrams": "18.9",
    "fatsPerHundredGrams": "12.4",
    "carbohydratePerHundredGrams": "0.0"
  }
}